version: '2'
services:
  notificacionesmicroservicio-mongodb:
    image: mongo:4.0.16
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/notificacionesmicroservicio/mongodb/:/data/db/
